version: '3.8'

services:
  app:
    build: .
    container_name: pmj-secure-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      # - ORIGIN=http://localhost:3000 # Only set this if you want to enforce a specific origin
      - DB_PATH=/app/data/passwords.db
      - BODY_SIZE_LIMIT=0
    volumes:
      - ./data:/app/data
