version: '3.8'

services:
  app:
    build: .
    container_name: pmj-secure-app
    restart: unless-stopped
    ports:
      - "3009:3000"
    environment:
      - ORIGIN=http://172.16.66.22:3009
      - DB_PATH=/app/data/passwords.db
      - BODY_SIZE_LIMIT=0
    volumes:
      - ./data:/app/data
